### PR TITLE
Fix/aboutus page

### PR DESCRIPTION
**Pull request by suanTech**
### Edited 9:57pm 
---
- Add authorise workshop endpoint for superuser
- Add verified badge to idea cards
TODO: decided whether to let superuser open workshops after verifying, or just show the badge

Screenshot 2024-04-07 at 9 58 51 pm

### Feature
---
- Add card for steps
- Divide section for readability
- Adjust font sizes
Screenshot 2024-04-07 at 8 26 47 pm
Screenshot 2024-04-07 at 8 27 28 pm

### CODE REVIEW

**Review by goyadev — CHANGES_REQUESTED** [review]
Looks great on the about us page! But we have a contrast issue with the pink text on the grey background. What classifies as large text? Can we bump up the font size? 
Screenshot 2024-04-08 at 4 25 12 pm
Screenshot 2024-04-08 at 4 31 58 pm

**Comment by suanTech** [comment]
Large text is 18px or over!

**Comment by goyadev** [comment]
> Large text is 18px or over!

I think we're at 16px from my browsing?

**Comment by suanTech** [comment]
Ohh ok I'll fix it!!

**Review by goyadev — APPROVED** [review]
Wew!

**Pull request merged**
