### PR TITLE
Feat/delete eoi

### PR DESCRIPTION
**Pull request by suanTech**
- add functionality to "Undo" the EOI.
- fix button text to be aligned with the naming rule.
- change button order

### CODE REVIEW

**Comment by goyadev** [comment]
I seem to be getting a 404 on deleting via the modal

Screenshot 2024-04-08 at 4 01 52 pm

**Comment by goyadev** [comment]
- Seems to have an issue in the promise?


Screenshot 2024-04-08 at 4 06 52 pm

**Review by goyadev — COMMENTED** [review]
see images in comments - seems to be erroring on delete

**Comment by suanTech** [comment]
The error has been fixed in the later PR -sorry!

**Comment by goyadev** [comment]
> The error has been fixed in the later PR -sorry!

All good! :)

**Pull request merged**
