### PR TITLE
Feat/hamburger

### PR DESCRIPTION
**Pull request by goyadev**
We have a functional hamburger! 🍔 Responsive, functional and working 
Screenshot 2024-03-24 at 6 48 44 pm
Screenshot 2024-03-24 at 6 48 37 pm
Screenshot 2024-03-24 at 6 48 26 pm
Screenshot 2024-03-24 at 6 48 19 pm

### CODE REVIEW

**Comment by cinchenx** [comment]
It looks amazing! 
I think because Suan pushed something as well, so you may have to pull and push again before you can merge the branch.

**Comment by goyadev** [comment]
Updates added as suggested @suanTech Will this be safe to merge the latest changes from development branch in?

**Comment by suanTech** [comment]
Yep! You can pull and merge development into this branch and push the merge commit!

**Review by suanTech — APPROVED** [review]
Great work!!

**Pull request merged**
